I forgot to write a graphics.cpp file. I have that now and just as a test I have a line and a rectangle in paint. When I run the makefile however, if says there's an undefined reference to those draw functions. It has to be the makefile because when I manually write the compile command it works.